#!/bin/bash

set -euo pipefail

current_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
ossuary_path="$(dirname "$current_dir")/../templates"

case "$1" in
-l)
    shift
    library_dir="$ossuary_path/$1"
    shift
    template_path="$ossuary_path/$1"
    shift
    sk -l "$library_dir" -f "$template_path" "$@"
    ;;
-h)
    script_name=$(basename "$0")
    cat <<EOF
Usage: $script_name [options] <file> [args]

Options:
    -l <dir>  Specify the library directory
    -h        Show this help message
EOF
    ;;
*)
    file_path="$ossuary_path/$1"
    shift
    sk -f "$file_path" "$@"
    ;;
esac
