#!/bin/bash
# shellcheck disable=SC2086

set -euo pipefail

current_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
ossuary_path=$(realpath "$(dirname "$current_dir")/../templates")

case "$1" in
-l)
    library_list=""
    while [[ $# -gt 0 ]]; do
        case "$1" in
        -l)
            shift
            library_list="$library_list -l $ossuary_path/$1"
            shift
            ;;
        *)
            break
            ;;
        esac
    done

    template_path="$ossuary_path/$1"
    shift
    sk ${library_list} -f "$template_path" "$@"
    ;;
-h)
    script_name=$(basename "$0")
    cat <<EOF
Usage: $script_name [options] <file> [args]

Options:
    -l [<path>|<name=path>]  Specify the library directory
    -h                       Show this help message
EOF
    ;;
*)
    file_path="$ossuary_path/$1"
    shift
    sk -f "$file_path" "$@"
    ;;
esac
