#!/bin/bash

set -euo pipefail

current_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
templates_path=$(realpath "$(dirname "$current_dir")/../templates")

find "${templates_path}" -type f |
    sed -E \
        -e "s#""${templates_path}/""##g" \
        -e '/^\./ d' \
        -e '/(^_|\/_)/ d'
