#!/bin/bash

set -euo pipefail

current_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
projects_path=$(realpath "$(dirname "$current_dir")/../projects")

find "${projects_path}" -type f -name "skelly.toml" |
    sed -E \
        -e "s#""${projects_path}/""##g" \
        -e "s#""/skelly.toml""##g"
