#!/bin/bash

set -euo pipefail

ossuary_dir="$HOME/code/ossuary/templates"

find "${ossuary_dir}" -type f |
    sed -E \
        -e "s#""${ossuary_dir}/""##g" \
        -e '/^\./ d' \
        -e '/(^_|\/_)/ d' \
        -e '/^README.md/ d'
